services:
  db:
    image: postgres:14
    container_name: local_postgres
    shm_size: 128mb
    ports:
      - "5432:${PG_PORT}"
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DB}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./scripts/init.sh:/docker-entrypoint-initdb.d/init.sh:rw
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - gobank
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB}"]    
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 15s
  
  metabase:
    image: metabase/metabase
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - gobank

  app:
    container_name: gobank-service
    build:
      context: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - PG_HOST=${PG_HOST}
      - PG_DB=${PG_DB}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_PORT=${PG_PORT}
    networks:
      - gobank
    restart: on-failure

networks:
  gobank:
    driver: bridge
