services:
  db:
    image: postgres
    container_name: local_postgres
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=tux123
      - POSTGRES_USER=gobank
      - POSTGRES_DB=gobank
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./scripts/init.sh:/docker-entrypoint-initdb.d/init.sh:rw
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - gobank
  
  metabase:
    image: metabase/metabase
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - gobank

  app:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    networks:
      - gobank

networks:
  gobank:
    driver: bridge